### ISSUE TITLE
Doesn't work for System as Root

### ISSUE THREAD

**Issue by penn5** [erfanoabdi/ROM_resigner#4]
```
Traceback (most recent call last):
  File "/home/penn/ROM_resigner/resign.py", line 33, in <module>
    xmldoc = minidom.parse(mac_permissions)
  File "/usr/lib64/python3.10/xml/dom/minidom.py", line 1988, in parse
    return expatbuilder.parse(file)
  File "/usr/lib64/python3.10/xml/dom/expatbuilder.py", line 913, in parse
    result = builder.parseFile(file)
  File "/usr/lib64/python3.10/xml/dom/expatbuilder.py", line 204, in parseFile
    buffer = file.read(16*1024)
AttributeError: 'NoneType' object has no attribute 'read'
```
Because /etc/ should be /system/etc/

**Comment by erfanoabdi** [comment]
run script on `<path to SAR>/system`
